before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version
      version-number
    - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
    - 10
cache: yarn
jobs:
    - stage: lint
      name: "Lint checks"
      script: yarn lint
    - stage: build
      name: "App build"
      script: yarn build
